# This is a basic workflow to help you get started with Actions

name: CI

on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  
  build:
  
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
  
    steps:

      - name: Get latest libnx release
        working-directory: nx
        run: |
          git clone https://github.com/switchbrew/libnx.git
          cd ./libnx
          git fetch --tags
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
          
      - name: Install libnx
        run: make install
    
      # Checks-out your repository
      - uses: actions/checkout@v2

      - name: Make
        run: make
          
      - uses: actions/upload-artifact@v2
        with:
          name: debug
          path: ./*.nro
